name: Build Components

on:
  push:
  pull_request:

env:
  ESMF_VERSION: 'release'
  STACK_DIR: $HOME/stack

jobs:
  build_components:
    name: Build Components
    runs-on: ubuntu-22.04

    steps:
    - name: Stack Directory Setup
      run: |
        mkdir -p ${STACK_DIR}/{include,lib,lib64,bin}
        export LD_LIBRARY_PATH=${STACK_DIR}/lib64:${STACK_DIR}/lib:${LD_LIBRARY_PATH}
        echo "STACK_DIR=${STACK_DIR}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        echo "${STACK_DIR}/bin" >> $GITHUB_PATH
    - name: Software Version
      env:
        ESMF_API_URL: https://api.github.com/repos/esmf-org/esmf/releases/latest
      run: |
        if [[ "$ESMF_VERSION" == 'release' ]]; then
          ESMF_VERSION=`curl --silent "${ESMF_API_URL}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
          echo "ESMF_VERSION ${ESMF_VERSION}"
          echo "ESMF_VERSION=${ESMF_VERSION}" >> $GITHUB_ENV
        fi
    - name: Cache Dependencies
      id: cache-libraries
      uses: actions/cache@v3
      with:
        path: ${STACK_DIR}
        key: stack-${RUNNER_OS}-esmf@${ESMF_VERSION}
    - name: Install HDF5
      env:
        CACHE_HIT: ${{steps.cache-build-dependencies.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          mkdir hdf5
          cd hdf5
          curl -L ${{env.hdf5-url}} | tar --strip-components=2 -xz
          ./configure --quiet --enable-silent-rules --enable-fortran --prefix=$STACK_DIR
          make all install
          cd ..
        fi
        echo "HDF5_DIR=$STACK_DIR" >> $GITHUB_ENV
    - name: Install NetCDF-C
      env:
        CACHE_HIT: ${{steps.cache-build-dependencies.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          mkdir netcdf-c
          cd netcdf-c
          curl -L ${{env.netcdf-url}} | tar --strip-components=1 -xz
          CPPFLAGS=-I${STACK_DIR}/include LDFLAGS=-L${STACK_DIR}/lib ./configure --quiet --enable-silent-rules --prefix=$STACK_DIR
          make all install
          cd ..
        fi
        echo "NETCDF_DIR=$STACK_DIR" >> $GITHUB_ENV
    - name: Install NetCDF-Fortran
      env:
        CACHE_HIT: ${{steps.cache-build-dependencies.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          mkdir netcdf-fortran
          cd netcdf-fortran
          curl -L ${{env.netcdff-url}} | tar --strip-components=1 -xz
          CPPFLAGS=-I${STACK_DIR}/include LDFLAGS=-L${STACK_DIR}/lib ./configure --quiet --enable-silent-rules --prefix=${STACK_DIR}
          make all install
        fi
        echo "NETCDFF_DIR=$STACK_DIR" >> $GITHUB_ENV
    - name: Install ESMF
      env:
        CACHE_HIT: ${{steps.cache-build-dependencies.outputs.cache-hit}}
        ESMF_COMM: "mpiuni"
        ESMF_BOPT: "O"
        ESMF_SITE: "default"
        ESMF_COMPILER: "gfortran"
        ESMF_OS: "Linux"
        ESMF_NETCDF: "split"
        ESMF_NETCDF_LIBPATH: "${STACK_DIR}/lib"
        ESMF_NETCDF_INCLUDE: "${STACK_DIR}/include"
        ESMF_NETCDF_LIBS: "-lnetcdf -lnetcdff"
        ESMF_INSTALL_MODDIR: "mod"
        ESMF_INSTALL_BINDIR: "bin"
        ESMF_INSTALL_LIBDIR: "lib"
        ESMF_INSTALL_PREFIX: "${STACK_DIR}"
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          mkdir esmf
          cd esmf
          export ESMF_DIR=`pwd`
          curl -L https://github.com/esmf-org/esmf/archive/refs/tags/v${ESMF_VERSION}.tar.gz | \
            tar --strip-components=1 -xz
          make all install
          cd ..
        fi
        echo "ESMFMKFILE=$STACK_DIR/lib/esmf.mk" >> $GITHUB_ENV
    - name: Build and Test
      run: |
        ESMX_Builder --test
